# Example theme: Dracula
foreground #f8f8f2
#background #282a36
cursor     #f8f8f0

color0  #000000
color1  #ff5555
color2  #50fa7b
color3  #f1fa8c
color4  #bd93f9
color5  #ff79c6
color6  #8be9fd
color7  #bbbbbb
color8  #555555
color9  #ff5555
color10 #50fa7b
color11 #f1fa8c
color12 #bd93f9
color13 #ff79c6
color14 #8be9fd
color15 #ffffff

window_margin_width     7


background_image        /home/dharmik/.config/kitty/1440x900-ana-de-armas-beach-4k_1629935602.jpg
background_image_layout cscaled
background_tint         0.9
background_tint_gaps    -10.0
window_border_width     1pt
active_border_color     #44ffff

map ctrl+shift+, move_window left
map ctrl+shift+. move_window right

